apiVersion: v1
kind: Pod
metadata:
  name: tpu7x-host-device-smart-chunking-benchmark
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
  - name: tpu-job
    image: python:3.12
    ports:
    - containerPort: 8431
    securityContext:
      privileged: false
    command:
    - bash
    - -c
    - |
      set -ex

      git clone https://github.com/linamy85/accelerator-microbenchmarks.git
      cd accelerator-microbenchmarks
      git checkout feature/pcie-transfer-smart-chunking
      pip install -r requirements.txt

      # Assume testing single chip throughput
      export TPU_VISIBLE_CHIPS=0
      bash ./Ironwood/scripts/run_host_device_benchmark.sh --config Ironwood/configs/host_device/host_device_smart_chunking.yaml

      sleep 36000

    resources:
      requests:
        google.com/tpu: 4
      limits:
        google.com/tpu: 4
